#!/bin/sh -e

ACTION=${2}

if [ "${ACTION}" != "connectivity-change" ] || \
   [ "${CONNECTIVITY_STATE}" != "FULL" ]; then
    exit 0
fi

# start after 1-2 minutes (AccuracySec defaults to 1min) to allow ntp to sync
# we can't use --unit=eos-phone-home.service here because eos-phone-home.timer already exists
# starting via systemd also ensures only one instance of the script is running
/bin/systemd-run --no-block --on-active=2m -- /bin/systemctl --no-block start eos-phone-home.service

exit 0
