#!/bin/sh -e

ACTION=${2}

if [ "${ACTION}" != "connectivity-change" ] || \
   [ "${CONNECTIVITY_STATE}" != "FULL" ]; then
    exit 0
fi

# start after 1-2 minutes (AccuracySec defaults to 1min) to allow ntp to sync
/bin/systemd-run --no-block --on-active=2m --unit=eos-phone-home.service

exit 0
