#!/bin/sh -e

if [ "$IFACE" != "lo" ] || \
   [ "$MODE" = "start" ] || \
   [ ! -f /var/lib/eos-phone-home/activated ]; then
    exit 0
fi

/bin/systemctl --no-block start eos-phone-home.service

exit 0
