#!/bin/bash
# Send an "I am alive" ping to Canonical. This is used for surveying how many
# original OEM installs are still existing on real machines. Note that this
# does not send any user specific data; it only transmits the operating system
# version (/var/lib/ubuntu_dist_channel), the machine product name, and a
# counter how many pings were sent.
#
# (C) 2010 Canonical Ltd.
# License: GPL v2 or later

set -e

COUNTFILE=/var/lib/send-install-count/counter
DCD=/var/lib/ubuntu_dist_channel
SCRIPT=http://census.canonical.com/submit

[ -e $DCD ] || exit 0

# get current count
if [ -e $COUNTFILE ]; then
    cur=$(< $COUNTFILE)
else
    cur=0
fi

# get DCD
channel=$(sed -n '/^[[:alnum:]]/ { p; q}' $DCD)

# get machine product name
product=$(< /sys/class/dmi/id/product_name) || product=''
product=${product/% *}

# report in
if ! wget -O /dev/null -q "$SCRIPT?count=$cur&dcd=$channel&product=$product"; then
    #echo "failed"
    exit 0
fi

# update counter
((cur=cur+1))
mkdir -p $(dirname $COUNTFILE)
echo $cur > $COUNTFILE


