#!/bin/bash
# Send an "I am alive" ping to Canonical. This is used for surveying how many
# original OEM installs are still existing on real machines. Note that this
# does not send any user specific data; it only transmits the operating system
# version (/var/lib/ubuntu_dist_channel), the machine product name, and a
# counter how many pings were sent.
#
# (C) 2010 Canonical Ltd.
# License: GPL v2 or later

set -e

COUNTFILE=/var/lib/send-install-count/counter
DCD=/var/lib/ubuntu_dist_channel
SCRIPT=http://poke.canonical.com/submit

[ -e $DCD ] || exit 0

# read release info
. /etc/lsb-release || :

# we need to know that we can write the count file, otherwise we'd send a
# perpetual stream of zeros
mkdir -p $(dirname $COUNTFILE)
if [ -e $COUNTFILE ]; then
    [ -w $COUNTFILE ]
else
    echo 0 > $COUNTFILE
fi

# get current count
cur=$(< $COUNTFILE)

# get DCD
channel=$(sed -n '/^[[:alnum:]]/ { p; q}' $DCD)

# get machine product name
product=$(< /sys/class/dmi/id/product_name) || product=''
product="${product%"${product##*[![:space:]]}"}"
# get machine vendor name
vendor=$(< /sys/class/dmi/id/sys_vendor) || vendor=''
vendor="${vendor%"${vendor##*[![:space:]]}"}"
# report in
if ! out=$(wget -O - -q "$SCRIPT?count=$cur&dcd=$channel&product=$product&vendor=$vendor&release=$DISTRIB_RELEASE"); then
    #echo "wget failed"
    exit 0
fi
if [ "$out" != "OK" ]; then
    #echo "invalid page"
    exit 0
fi

# update counter
((cur=cur+1))
echo $cur > $COUNTFILE


