#!/bin/bash
# Send an "I am alive" ping to Ubuntu. This is used for surveying how many
# original OEM installs are still existing on real machines. Note that this
# does not send any machine or user specific data; it only transmits the
# operating system version (/var/lib/ubuntu_dist_channel) and a counter how
# many pings were sent.
#
# (C) 2010 Canonical Ltd.

set -e

COUNTFILE=/var/lib/send-install-count/counter
DCD=/var/lib/ubuntu_dist_channel
SCRIPT=http://census.canonical.com/submit

[ -e $DCD ] || exit 0

# get current count
if [ -e $COUNTFILE ]; then
    cur=$(< $COUNTFILE)
else
    cur=0
fi

((cur=cur+1))

# update counter
mkdir -p $(dirname $COUNTFILE)
echo $cur > $COUNTFILE

# get DCD
channel=$(sed -n '/^[[:alnum:]]/ { p; q}' $DCD)

wget -O - -q "$SCRIPT?count=$cur&dcd=$channel"
