#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling census while in livefs..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

rm -f /root/etc/cron.daily/send-census

log_end_msg
