#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling poke while in livefs..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

rm -f /root/etc/cron.daily/send-poke
rm -f /root/etc/cron.weekly/send-poke
rm -f /root/etc/cron.monthly/send-poke

log_end_msg
